mediaGenres = [
    'Action',
  'Adventure',
  'Comedy',
  'Drama',
  'Sci-Fi',
  'Mystery',
  'Supernatural',
  'Fantasy',
  'Sports',
  'Romance',
  'Slice of Life',
  'Horror',
  'Psychological',
  'Thriller',
  'Ecchi',
  'Mecha',
  'Music',
  'Mahou Shoujo',
  'Hentai'
]; 
mediaFormat = {
    TV: 'TV',
    TV_SHORT: 'TV Shorts',
    MOVIE: 'Movie',
    SPECIAL: 'Special',
    ONA: 'ONA',
    OVA: 'OVA',
    MUSIC: 'Music',
    MANGA: 'Manga',
    NOVEL: 'Light Novel',
    ONE_SHOT: 'One Shot Manga'
}; 

malGenres = {
    action: 1,
    adventure: 2,
    cars: 3,
    comedy: 4,
    dementia: 5,
    demons: 6,
    mystery: 7,
    drama: 8,
    ecchi: 9,
    fantasy: 10,
    game: 11,
    hentai: 12,
    historical: 13,
    horror: 14,
    kids: 15,
    magic: 16,
    'martial arts': 17,
    mecha: 18,
    music: 19,
    parody: 20,
    samurai: 21,
    romance: 22,
    school: 23,
    'sci-fi': 24,
    shoujo: 25,
    'shoujo ai': 26,
    shounen: 27,
    'shounen ai': 28,
    space: 29,
    sports: 30,
    'super power': 31,
    vampire: 32,
    yaoi: 33,
    yuri: 34,
    harem: 35,
    'slice of life': 36,
    supernatural: 37,
    military: 38,
    police: 39,
    psychological: 40,
    thriller: 41,
    seinen: 42,
    josei: 43
  };

  months = [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December'
  ];
  weeks = [
    'sunday',
    'monday',
    'tuesday',
    'wednesday',
    'thursday',
    'friday',
    'saturday'
  ];
  langFlags = [
    { lang: 'Hungarian', flag: '🇭🇺' },
    { lang: 'Japanese', flag: '🇯🇵' },
    { lang: 'French' , flag: '🇫🇷' },
    { lang: 'Russian' , flag:'🇷🇺' },
    { lang: 'German', flag: '🇩🇪' },
    { lang: 'English', flag: '🇺🇸' },
    { lang: 'Italian', flag: '🇮🇹' },
    { lang: 'Spanish', flag: '🇪🇸' },
    { lang: 'Korean', flag: '🇰🇷' },
    { lang: 'Chinese', flag: '🇨🇳' },
    { lang: 'Brazilian', flag: '🇧🇷' }
  ];
module.exports = [
    mediaGenres, 
    mediaFormat, 
    malGenres,
    months, 
    weeks, 
    langFlags

]