module.exports = {
    Archive: require('./Archive'),
    ArchiveAll: require('./ArchiveAll'),
    ArchiveImages: require('./ArchiveImages'),
    AtlaTopics: require('./AtlaTopics'),
    DuplicateBending: require('./DuplicateBending'),
    GetArchive: require('./GetArchive'),
    IgnoreChannel: require('./IgnoreChannel'),
    JoinMessages: require('./JoinMessages'),
    LoadSuggestion: require('./LoadSuggestion'),
    LokTopics: require('./LokTopics'),
    Members: require('./Members'),
    MessageContext: require('./MessageContext'),
    MigrateAvatarTopics: require('./MigrateAvatarTopics'),
    Nick: require('./Nick'),
    // Prefix: require('./Prefix'),
    // Setnick: require('./Setnick'),
    Respond: require('./Respond'),
    SetLogChannel: require('./SetLogChannel'),
    Topics: require('./Topics'),
    ViewSuggestion: require('./ViewSuggestion'),
    WeBo: require('./WelcomeButtons')
};
