module.exports = {
    AddJoinMessages: require('./AddJoinMessages'),
    AddTopic: require('./AddTopic'),
    Archive: require('./Archive'),
    ArchiveAll: require('./ArchiveAll'),
    ArchiveImages: require('./ArchiveImages'),
    DuplicateBending: require('./DuplicateBending'),
    GetArchive: require('./GetArchive'),
    IgnoreChannel: require('./IgnoreChannel'),
    JoinMessagesList: require('./JoinMessagesList'),
    LoadSuggestion: require('./LoadSuggestion'),
    Members: require('./Members'),
    MessageContext: require('./MessageContext'),
    Nick: require('./Nick'),
    // Prefix: require('./Prefix'),
    // Setnick: require('./Setnick'),
    Respond: require('./Respond'),
    SetLogChannel: require('./SetLogChannel'),
    TopicsList: require('./TopicsList'),
    ViewSuggestion: require('./ViewSuggestion'),
    WeBo: require('./WelcomeButtons')
};
