module.exports = {
    AddAcks: require('./AddAcks'),
    AutoBanner: require('./AutoBanner'),
    Build: require('./Build'),
    ClearIgnoredTopics: require('./ClearIgnoredTopics'),
    Config: require('./Configure'),
    DeleteAcks: require('./DeleteAcks'),
    EditWiki: require('./EditWiki'),
    Eval: require('./Eval'),
    Exec: require('./Exec'),
    LoadPermissions: require('./LoadPermissions'),
    Restart: require('./Restart'),
    ScrapeLeaderboard: require('./ScrapeLeaderboard'),
    SetAvatar: require('./SetAvatar'),
    SetGame: require('./SetGame'),
    Speedtest: require('./Speedtest'),
    Staff: require('./Staff'),
    TatsuTest: require('./Tatsu'),
    TestJoinMessages: require('./TestJoinMessages'),
    UserDB: require('./UserDB'),
};
