module.exports = {
    AddAcks: require('./AddAcks'),
    AutoBanner: require('./AutoBanner'),
    Build: require('./Build'),
    Config: require('./Configure'),
    DeleteAcks: require('./DeleteAcks'),
    Eval: require('./Eval'),
    Exec: require('./Exec'),
    LoadPermissions: require('./LoadPermissions'),
    Restart: require('./Restart'),
    ServerStats: require('./ServerStats'),
    SetAvatar: require('./SetAvatar'),
    SetGame: require('./SetGame'),
    Speedtest: require('./Speedtest'),
    Staff: require('./Staff'),
    Superbending: require('./Superbending'),
};
